- hosts: local
  user: vagrant
  sudo: true
  vars:
    blog_title: A Wordberry Blog
    admin_email: test@pixelistik.de
    admin_password: test
  tasks:
    - name: update apt repo
      action: apt update-cache=yes cache_valid_time=3600

    - name: install nginx
      action: apt name=nginx state=installed

    - name: install php
      action: apt name=php5-fpm state=installed

    - name: install mysql client
      action: apt name=php5-mysql state=installed
      notify: restart php

    - name: install gd
      action: apt name=php5-gd state=installed

    - name: install php5-curl
      action: apt name=php5-curl state=installed

    - name: install apc
      action: apt name=php-apc state=installed
      notify: restart php

    - name: install mysql server
      action: apt name=mysql-server state=installed

    - name: install php5-cli
      action: apt name=php5-cli state=installed

    - name: install curl
      action: apt name=curl state=installed

    - name: install git
      action: apt name=git state=installed

    - name: download wp-cli installer
      get_url: url=https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh dest=/tmp/wp-cli-installer.sh mode=0755

    - name: install wp-cli
      shell: INSTALL_DIR='/usr/share/wp-cli' /tmp/wp-cli-installer.sh creates=/usr/share/wp-cli

    - name: symlink wp-cli to /usr/bin
      action: file src=/usr/share/wp-cli/bin/wp dest=/usr/bin/wp state=link

    - name: create wordpress directory
      file: path=/var/www/wordpress state=directory

    - name: install wordpress
      command: wp core download chdir=/var/www/wordpress creates=/var/www/wordpress/wp-content

    - name: set root as owner of wordpress directory
      file: path=/var/www/wordpress state=directory owner=root group=root recurse=yes

    - name: create upload directory with owner www-data
      file: path=/var/www/wordpress/wp-content/uploads state=directory owner=www-data group=www-data

    - name: create nginx site
      action: template src=nginx-site.j2 dest=/etc/nginx/sites-available/wordpress owner=www-data group=www-data
      notify: restart nginx

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-available/default state=absent
      notify: restart nginx

    - name: activate nginx site
      action: file src=/etc/nginx/sites-available/wordpress dest=/etc/nginx/sites-enabled/wordpress owner=www-data group=www-data state=link
      notify: restart nginx

    - name: install mysql support for python
      action: apt name=python-mysqldb state=installed

    - name: create wordpress database
      mysql_db: name=wordpress

    - name: create wordpress configuration
      shell: echo 'define("WP_SITEURL", "http://" . $_SERVER["HTTP_HOST"]);define("WP_HOME", "http://" . $_SERVER["HTTP_HOST"]);'|wp core config --dbname=wordpress --dbuser=root chdir=/var/www/wordpress --extra-php creates=/var/www/wordpress/wp-config.php

    - name: set up wordpress admin and blog
      command: wp core install --title={{ blog_title }} --admin_email={{ admin_email }} --admin_password={{ admin_password }} chdir=/var/www/wordpress

    - name: set up wordpress URL structure
      command: wp rewrite structure '/%year%/%postname%' chdir=/var/www/wordpress

    - name: install varnish
      action: apt name=varnish state=installed

    - name: varnish options
      action: template src=varnish-options.j2 dest=/etc/default/varnish
      notify: restart varnish

    - name: varnish config
      action: template src=varnish-config.vcl.j2 dest=/etc/varnish/wordpress.vcl
      notify: restart varnish

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted

    - name: restart php
      action: service name=php5-fpm state=restarted

    - name: restart varnish
      action: service name=varnish state=restarted